force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>Represents a work order generated from a customer call to perform plumbing work.</description>
    <label>Work_Order</label>
    <nameField>
        <label>Work_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Complete address where the service will be made.</description>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client that required the service. If is public, can be generated automatically</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work_Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Preferred_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Time__c</fullName>
    <label>Preferred Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In_Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkOrderIntakeController.cls
public with sharing class WorkOrderIntakeController {
    @AuraEnabled
    public static void submitWorkOrder(
        String name, 
        String phone, 
        String email, 
        String address, 
        String description, 
        String preferredTime,
        Decimal estimatedCost,
        List<Id> fileIds)
        {

        //Checks if the contact being register, already exists and save your id.
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = :email LIMIT 1];
        Contact contact;

        if (!contacts.isEmpty()) {
            contact = contacts[0];
        } else {
            contact = new Contact(
                LastName = name,
                Email = email,
                Phone = phone
            );
            insert contact;
        }


        //Create work order
        Work_Order__c order = new Work_Order__c(
            Customer__c = contact.Id,
            Address__c = address,
            Description__c = description,
            Status__c = 'New',
            Preferred_Time__c = preferredTime,
            Estimated_Cost__c = estimatedCost
        );

        insert order;

        //Relate files
        if (fileIds != null && fileIds.size() > 0){
            List<ContentDocumentLink> links = new List<ContentDocumentLink>();
            for (Id docId : fileIds){
                links.add(new ContentDocumentLink(
                    ContentDocumentId = docId,
                    LinkedEntityId = order.Id,
                    ShareType = 'V'
                ));
            }
            insert links;
        }

    }   

    //Future feature: email sent logic
}