force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>Represents a work order generated from a customer call to perform plumbing work.</description>
    <label>Work_Order</label>
    <nameField>
        <label>Work_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client that required the service. If is public, can be generated automatically</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work_Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Preferred_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Time__c</fullName>
    <label>Preferred Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailAlertAction.cls
public with sharing class SendEmailAlertAction{
    @InvocableMethod(label='Enviar Email de Confirmação')
    public static void send(List<Id> workOrderIds){
        List<Work_Order__c> orders = [
            SELECT Id, Name, Customer__r.Email, Customer__r.Name, Estimated_Cost__c, Preferred_Time__c
            FROM Work_Order__c
            WHERE Id IN :workOrderIds
        ];
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Work_Order__c order : orders){
            if(order.Customer__r != null && String.isNotBlank(order.Customer__r.Email)) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] {order.Customer__r.Email});
                mail.setSubject('Confirmação de Agendamento - Ordem de Serviço ' + order.Name);
                mail.setPlainTextBody(
                    'Hello ' + order.Customer__r.Name + ',\n\n' +
                    'Your work order has been succefully register!\n\n' +
                    '📋 Details:\n' +
                    '- Number: ' + order.Name + '\n' +
                    '- Preferred Time: ' + String.valueOf(order.Preferred_Time__c) + '\n' +
                    '- Estimated Cost: R$ ' + String.valueOf(order.Estimated_Cost__c) + '\n\n' +
                    'Thank you for chosing Plumbers CRM!\n\n' +
                    'Sincerely,\nPlumbers CRM Service.'                    
                );
                emails.add(mail);
            }
        }
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }
}